version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: laravel-app
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    environment:
      - PUID=1000
      - PGID=1000
    networks: [laravel]

  nginx:
    image: nginx:1.25-alpine
    container_name: laravel-nginx
    depends_on: [app]
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks: [laravel]

  node:
    image: node:18-alpine
    container_name: laravel-node
    working_dir: /app
    environment:
      - CHOKIDAR_USEPOLLING=1         
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    command: sh -c "npm ci && npm run watch -- --watch-options-poll=1000"
    networks: [laravel]

networks:
  laravel:
    driver: bridge

volumes:
  node_modules:
